# add doxygen docs
# to get paraview debian/build properly on top of vtk we now add this as a symlink 
# in the python-vtk6 package 
# /usr/lib/*/python2.7/site-packages/vtk/*
CMake/TopologicalSort.cmake usr/lib/cmake/vtk-6.3/
CMake/exportheader.cmake.in usr/lib/cmake/vtk-6.3/
CMake/vtkGroups.cmake usr/lib/cmake/vtk-6.3/
CMake/vtkTesting*.cmake	usr/lib/cmake/vtk-6.3/
Common/Core/vtkPointAccumulator.hxx usr/include/vtk-6.3/
Common/DataModel/vtkMarchingCubesTriangleCases.h usr/include/vtk-6.3/
Filters/Statistics/vtkStatisticsAlgorithmPrivate.h usr/include/vtk-6.3/
IO/Import/vtk3DS.h usr/include/vtk-6.3/
Testing/Core/vtkTestDriver.h usr/include/vtk-6.3
Testing/Core/vtkTestUtilities.h usr/include/vtk-6.3/
Testing/Core/vtkTesting*.h usr/include/vtk-6.3
Testing/Rendering/vtkRegressionTestImage.h usr/include/vtk-6.3/
Testing/Rendering/vtkTesting*.h usr/include/vtk-6.3
ThirdParty/ftgl/src/FTGL.h usr/include/vtk-6.3/
Wrapping/Java/JavaDependencies.cmake.in usr/lib/cmake/vtk-6.3/
debian/build/ThirdParty/ftgl/vtkftglConfig.h usr/include/vtk-6.3/
debian/build/ThirdParty/netcdf/vtk_netcdf.h usr/include/vtk-6.3/
debian/build/ThirdParty/netcdf/vtk_netcdfcpp.h usr/include/vtk-6.3/
debian/build/lib/cmake/vtk-6.3/Modules/*-Headers.cmake	usr/lib/cmake/vtk-6.3/Modules/
usr/include/vtk-6.3                    usr/include
usr/lib/*/*.so
usr/lib/cmake/vtk-6.3
usr/share/doc/vtk-6.3/doxygen/* /usr/share/vtk-6.3/doxygen/
