# add doxygen docs
# to get paraview debian/build properly on top of vtk
CMake/TopologicalSort.cmake usr/lib/cmake/vtk-6.1/
CMake/exportheader.cmake.in usr/lib/cmake/vtk-6.1/
CMake/vtkGroups.cmake usr/lib/cmake/vtk-6.1/
CMake/vtkTesting*.cmake	usr/lib/cmake/vtk-6.1/
Common/Core/vtkPointAccumulator.hxx usr/include/vtk-6.1/
Common/DataModel/vtkMarchingCubesCases.h usr/include/vtk-6.1/
Filters/Statistics/vtkStatisticsAlgorithmPrivate.h usr/include/vtk-6.1/
IO/Import/vtk3DS.h usr/include/vtk-6.1/
Testing/Core/vtkTestDriver.h usr/include/vtk-6.1
Testing/Core/vtkTestUtilities.h usr/include/vtk-6.1/
Testing/Core/vtkTesting*.h usr/include/vtk-6.1
Testing/Rendering/vtkRegressionTestImage.h usr/include/vtk-6.1/
Testing/Rendering/vtkTesting*.h usr/include/vtk-6.1
ThirdParty/ftgl/src/FTGL.h usr/include/vtk-6.1/
debian/build/ThirdParty/netcdf/vtk_netcdf.h usr/include/vtk-6.1/
debian/build/ThirdParty/netcdf/vtk_netcdfcpp.h usr/include/vtk-6.1/
Wrapping/Java/JavaDependencies.cmake.in usr/lib/cmake/vtk-6.1/
debian/build/ThirdParty/ftgl/vtkftglConfig.h usr/include/vtk-6.1/
debian/build/Utilities/Doxygen/doc/html usr/share/doc/libvtk6-dev
debian/build/lib/cmake/vtk-6.1/Modules/*-Headers.cmake	usr/lib/cmake/vtk-6.1/Modules/
usr/include/vtk-6.1                    usr/include
usr/lib/*/*.so
usr/lib/cmake/vtk-6.1
